---
name: Auto-Create PR

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - chore/*
      - hotfix/*
      - refactor/*
  workflow_dispatch:

jobs:
  create-pr:
    name: Create PR
    # yamllint disable-line rule:line-length
    uses: worgarside/github-config-files/.github/workflows/__create_pull_request.yml@main
    with:
      base-ref-name: ${{ github.event.repository.default_branch }}
      head-ref-name: ${{ github.ref_name }}
      pr-title: ${{ github.event.head_commit.message }}
      pr-draft: true
      update-pr-body-if-exists: true
    secrets: inherit
